// BHAYA INDIA — E-Commerce Category & Subcategory Taxonomy
// Comprehensive hierarchy with English, Hindi, search aliases, transliterations, and related terms.

export interface SubcategoryDef {
  id: string;
  slug: string;
  name_en: string;
  name_hi: string;
  parentSlug: string;
  searchAliases: string[];
  relatedTerms: string[];
  shopifyCollectionHandle?: string;
  status: "active" | "coming_soon";
}

export interface CategoryDef {
  id: string;
  slug: string;
  name_en: string;
  name_hi: string;
  parent: string | null;
  tagline_en: string;
  tagline_hi: string;
  description_en: string;
  description_hi: string;
  image: string;
  subcategories: SubcategoryDef[];
  searchAliases: string[];
  relatedTerms: string[];
  shopifyCollectionHandle?: string;
  status: "active" | "coming_soon";
}

export const CATEGORIES_TAXONOMY: CategoryDef[] = [
  // 1. FESTIVAL
  {
    id: "cat-festival",
    slug: "festival",
    name_en: "Festival",
    name_hi: "त्योहार",
    parent: null,
    tagline_en: "Auspicious Indian Festivities & Rituals",
    tagline_hi: "पवित्र भारतीय पर्व एवं परंपराएं",
    description_en: "Authentic festival samagri, ritual essentials, decorative accents, and festive gifts celebrating India's rich cultural heritage.",
    description_hi: "प्रामाणिक त्योहार सामग्री, पूजा अनुष्ठान वस्तुएं, उत्सव सजावट और भारत की समृद्ध परंपराओं से जुड़े उपहार।",
    image: "/assets/hero-editorial.jpg",
    shopifyCollectionHandle: "festival",
    status: "active",
    searchAliases: [
      "festival",
      "festivals",
      "त्योहार",
      "त्यौहार",
      "उत्सव",
      "पर्व",
      "festive",
      "tyohar",
      "utsav",
      "parv",
      "parva",
    ],
    relatedTerms: [
      "Puja",
      "Puja Samagri",
      "Holi",
      "Diwali",
      "Navratri",
      "Ganesh Puja",
      "Karwa Chauth",
      "Wedding",
      "Festival Decoration",
      "Hampers",
      "पूजा",
      "दिवाली",
      "होली",
      "करवा चौथ",
    ],
    subcategories: [
      {
        id: "sub-fest-puja",
        slug: "puja-items",
        name_en: "Puja Items",
        name_hi: "पूजा सामग्री",
        parentSlug: "festival",
        shopifyCollectionHandle: "puja-samagri",
        status: "active",
        searchAliases: [
          "puja",
          "pooja",
          "puja items",
          "pooja items",
          "puja samagri",
          "pooja samagri",
          "पूजा",
          "पूजा सामग्री",
          "हवन सामग्री",
          "havan",
          "havan samagri",
          "brass diya",
          "diya",
          "camphor",
          "dhoop",
          "agarbatti",
          "aasan",
        ],
        relatedTerms: ["Diya", "Incense", "Havan", "Gangajal", "Roli", "Akshat"],
      },
      {
        id: "sub-fest-holi",
        slug: "holi",
        name_en: "Holi",
        name_hi: "होली",
        parentSlug: "festival",
        shopifyCollectionHandle: "holi",
        status: "active",
        searchAliases: [
          "holi",
          "holy",
          "होली",
          "रंग",
          "गुलाल",
          "पिचकारी",
          "gulal",
          "herbal gulal",
          "organic colors",
          "pichkari",
          "water gun",
          "holi hamper",
          "thandai",
        ],
        relatedTerms: ["Organic Gulal", "Pichkari", "Holi Hampers", "Herbal Colors"],
      },
      {
        id: "sub-fest-diwali",
        slug: "diwali",
        name_en: "Diwali",
        name_hi: "दिवाली",
        parentSlug: "festival",
        shopifyCollectionHandle: "diwali",
        status: "active",
        searchAliases: [
          "diwali",
          "deepawali",
          "deepavali",
          "दिवाली",
          "दीपावली",
          "दीपक",
          "दीये",
          "लक्ष्मी पूजा",
          "lakshmi puja",
          "ganesh lakshmi",
          "brass diyas",
          "terracotta diya",
          "decorative lights",
          "rangoli",
        ],
        relatedTerms: ["Brass Diya", "Lakshmi Ganesh Idol", "Deepawali Gifting", "Toran"],
      },
      {
        id: "sub-fest-navratri",
        slug: "navratri",
        name_en: "Navratri",
        name_hi: "नवरात्र",
        parentSlug: "festival",
        shopifyCollectionHandle: "navratri",
        status: "active",
        searchAliases: [
          "navratri",
          "navratra",
          "navaratri",
          "नवरात्र",
          "नवरात्रि",
          "दुर्गा पूजा",
          "durga puja",
          "mata ki chunri",
          "garba",
          "dandiya",
          "fasting items",
          "vrat samagri",
          "kanya pujan",
        ],
        relatedTerms: ["Mata Chunri", "Akhand Jyot", "Dandiya Sticks", "Vrat Samagri"],
      },
      {
        id: "sub-fest-ganesh",
        slug: "ganesh-puja",
        name_en: "Ganesh Puja",
        name_hi: "गणेश पूजा",
        parentSlug: "festival",
        shopifyCollectionHandle: "ganesh-puja",
        status: "active",
        searchAliases: [
          "ganesh puja",
          "ganesha",
          "ganpati",
          "ganesh utsav",
          "ganesh chaturthi",
          "गणेश पूजा",
          "गणपति",
          "गणेश चतुर्थी",
          "vinayaka",
          "modak",
          "ganpati idol",
          "eco friendly ganesha",
        ],
        relatedTerms: ["Ganesh Idol", "Modak Mould", "Ganesh Puja Kit", "Puja Aasan"],
      },
      {
        id: "sub-fest-karwa",
        slug: "karwa-chauth",
        name_en: "Karwa Chauth",
        name_hi: "करवा चौथ",
        parentSlug: "festival",
        shopifyCollectionHandle: "karwa-chauth",
        status: "active",
        searchAliases: [
          "karwa chauth",
          "karva chauth",
          "karwachauth",
          "karvachauth",
          "karwa",
          "karva",
          "करवा चौथ",
          "करवा",
          "छलनी",
          "करवा चौथ थाली",
          "karwa chauth thali",
          "channi",
          "chalni",
          "karwa chauth puja kit",
          "karwa chauth gift",
          "vrat samagri",
          "sargi",
          "sargi hamper",
        ],
        relatedTerms: ["Karwa Chauth Thali", "Chalni", "Karwa Lota", "Vrat Katha Book", "Sargi Hamper"],
      },
      {
        id: "sub-fest-decor",
        slug: "festival-decoration",
        name_en: "Festival Decoration",
        name_hi: "त्योहार सजावट",
        parentSlug: "festival",
        shopifyCollectionHandle: "festival-decoration",
        status: "active",
        searchAliases: [
          "festival decoration",
          "festive decor",
          "त्योहार सजावट",
          "सजावट",
          "तोरण",
          "बंदनवार",
          "toran",
          "bandhanwar",
          "door hanging",
          "fairy lights",
          "rangoli colors",
          "urli",
          "brass urli",
        ],
        relatedTerms: ["Toran", "Bandhanwar", "Decorative Urli", "Floating Candles"],
      },
      {
        id: "sub-fest-wedding",
        slug: "wedding-marriage-items",
        name_en: "Wedding & Marriage Related Items",
        name_hi: "विवाह एवं शादी संबंधी सामग्री",
        parentSlug: "festival",
        shopifyCollectionHandle: "wedding-marriage-items",
        status: "active",
        searchAliases: [
          "wedding",
          "marriage",
          "shaadi",
          "shadi",
          "vivaah",
          "vivah",
          "शादी",
          "विवाह",
          "वेडिंग",
          "विवाह सामग्री",
          "shagun",
          "shagun envelope",
          "wedding trunk",
          "bridal kit",
          "haldi kumkum",
          "varmala",
        ],
        relatedTerms: ["Shagun Envelopes", "Bridal Trunks", "Haldi Platter", "Wedding Favors"],
      },
      {
        id: "sub-fest-gifts",
        slug: "gift-items",
        name_en: "Gift Items",
        name_hi: "उपहार सामग्री",
        parentSlug: "festival",
        shopifyCollectionHandle: "gift-items",
        status: "active",
        searchAliases: [
          "gift",
          "gifts",
          "gift items",
          "उपहार",
          "उपहार सामग्री",
          "गिफ्ट",
          "गिफ्ट आइटम",
          "uphar",
          "return gift",
          "token gift",
          "corporate gift",
        ],
        relatedTerms: ["Corporate Gifts", "Personalized Boxes", "Return Gifts", "Keepsakes"],
      },
      {
        id: "sub-fest-hampers",
        slug: "festival-hampers",
        name_en: "Festival Hampers",
        name_hi: "त्योहार उपहार",
        parentSlug: "festival",
        shopifyCollectionHandle: "festival-hampers",
        status: "active",
        searchAliases: [
          "festival hampers",
          "festive hamper",
          "gift hampers",
          "त्योहार उपहार",
          "त्योहार हैम्पर",
          "उपहार हैम्पर",
          "dry fruit hamper",
          "sweet box",
          "curated trunk",
        ],
        relatedTerms: ["Gourmet Hampers", "Brass Hamper Trunks", "Dry Fruit Boxes"],
      },
      {
        id: "sub-fest-other",
        slug: "other-festival-products",
        name_en: "Other Festival Products",
        name_hi: "अन्य त्योहार उत्पाद",
        parentSlug: "festival",
        shopifyCollectionHandle: "other-festival-products",
        status: "active",
        searchAliases: [
          "other festival",
          "other festival products",
          "अन्य त्योहार",
          "अन्य त्योहार उत्पाद",
          "regional festival",
          "chath puja",
          "rakhi",
          "bhai dooj",
          "makar sankranti",
        ],
        relatedTerms: ["Raksha Bandhan", "Chhath Puja", "Pongal", "Makar Sankranti"],
      },
    ],
  },

  // 2. RETAIL
  {
    id: "cat-retail",
    slug: "retail",
    name_en: "Retail",
    name_hi: "रिटेल",
    parent: null,
    tagline_en: "Everyday Household & General Merchandise",
    tagline_hi: "दैनिक घरेलू एवं जनरल स्टोर उत्पाद",
    description_en: "Everyday essentials, household utilities, personal care, and stationery for modern Indian homes and retailers.",
    description_hi: "भारतीय घरों और खुदरा व्यापारियों के लिए दैनिक उपयोग, घरेलू सामान, पर्सनल केयर और स्टेशनरी उत्पाद।",
    image: "/assets/category-textiles.jpg",
    shopifyCollectionHandle: "retail",
    status: "active",
    searchAliases: ["retail", "रिटेल", "खुदरा", "general store", "household", "home goods"],
    relatedTerms: ["Daily Use", "Kitchen", "Stationery", "Personal Care", "Home Essentials"],
    subcategories: [
      {
        id: "sub-ret-daily",
        slug: "daily-use",
        name_en: "Daily Use",
        name_hi: "दैनिक उपयोग",
        parentSlug: "retail",
        status: "active",
        searchAliases: ["daily use", "दैनिक उपयोग", "everyday use", "routine products"],
        relatedTerms: ["Towels", "Soaps", "Daily Necessities"],
      },
      {
        id: "sub-ret-household",
        slug: "household",
        name_en: "Household",
        name_hi: "घरेलू उत्पाद",
        parentSlug: "retail",
        status: "active",
        searchAliases: ["household", "household products", "घरेलू", "घरेलू उत्पाद", "home utility"],
        relatedTerms: ["Cleaning", "Organizers", "Buckets", "Storage"],
      },
      {
        id: "sub-ret-general",
        slug: "general-store",
        name_en: "General Store",
        name_hi: "जनरल स्टोर",
        parentSlug: "retail",
        status: "active",
        searchAliases: ["general store", "जनरल स्टोर", "merchandise", "kirana essentials"],
        relatedTerms: ["Batteries", "Tape", "Sundries"],
      },
      {
        id: "sub-ret-kitchen",
        slug: "kitchen",
        name_en: "Kitchen",
        name_hi: "रसोई सामग्री",
        parentSlug: "retail",
        status: "active",
        searchAliases: ["kitchen", "kitchenware", "रसोई", "रसोई सामग्री", "utensils", "brass cookware", "copper bottle"],
        relatedTerms: ["Copper Bottles", "Brass Utensils", "Cutlery", "Spice Jars"],
      },
      {
        id: "sub-ret-home",
        slug: "home-essentials",
        name_en: "Home Essentials",
        name_hi: "गृह उपयोगी वस्तुएं",
        parentSlug: "retail",
        status: "active",
        searchAliases: ["home essentials", "गृह उपयोगी", "home living", "cushions", "bedsheets"],
        relatedTerms: ["Bedsheets", "Curtains", "Cushions"],
      },
      {
        id: "sub-ret-care",
        slug: "personal-care",
        name_en: "Personal Care",
        name_hi: "पर्सनल केयर",
        parentSlug: "retail",
        status: "active",
        searchAliases: ["personal care", "पर्सनल केयर", "self care", "grooming", "ayurvedic oils"],
        relatedTerms: ["Herbal Soaps", "Hair Oil", "Care Kits"],
      },
      {
        id: "sub-ret-stationery",
        slug: "stationery",
        name_en: "Stationery",
        name_hi: "स्टेशनरी",
        parentSlug: "retail",
        status: "active",
        searchAliases: ["stationery", "स्टेशनरी", "notebook", "pens", "office supplies", "registers"],
        relatedTerms: ["Leather Notebooks", "Executive Diaries", "Gel Pens"],
      },
      {
        id: "sub-ret-other",
        slug: "other-retail-products",
        name_en: "Other Retail Products",
        name_hi: "अन्य रिटेल उत्पाद",
        parentSlug: "retail",
        status: "active",
        searchAliases: ["other retail", "अन्य रिटेल उत्पाद", "general retail"],
        relatedTerms: ["Seasonal Retail", "Promo Packs"],
      },
    ],
  },

  // 3. AGRO
  {
    id: "cat-agro",
    slug: "agro",
    name_en: "Agro",
    name_hi: "कृषि",
    parent: null,
    tagline_en: "Farming Supplies, Seeds & Rural Produce",
    tagline_hi: "कृषि उत्पाद, खेती सामग्री एवं बीज",
    description_en: "Direct farm inputs, seeds, agricultural implements, and verified rural opportunities empowering farmers across India.",
    description_hi: "सीधे कृषि इनपुट, गुणवत्तापूर्ण बीज, उपकरण और भारतीय किसानों को सशक्त करने वाले कृषि अवसर।",
    image: "/assets/category-stationery.jpg",
    shopifyCollectionHandle: "agro",
    status: "active",
    searchAliases: ["agro", "agriculture", "कृषि", "खेती", "किसान", "farming", "krishi"],
    relatedTerms: ["Seeds", "Farming Supplies", "Tools", "Rural Products"],
    subcategories: [
      {
        id: "sub-agro-products",
        slug: "agricultural-products",
        name_en: "Agricultural Products",
        name_hi: "कृषि उत्पाद",
        parentSlug: "agro",
        status: "active",
        searchAliases: ["agricultural products", "कृषि उत्पाद", "farm produce", "crops"],
        relatedTerms: ["Grains", "Pulses", "Raw Produce"],
      },
      {
        id: "sub-agro-supplies",
        slug: "farming-supplies",
        name_en: "Farming Supplies",
        name_hi: "खेती सामग्री",
        parentSlug: "agro",
        status: "active",
        searchAliases: ["farming supplies", "खेती सामग्री", "fertilizer", "bio manure", "compost"],
        relatedTerms: ["Organic Fertilizers", "Crop Protectors"],
      },
      {
        id: "sub-agro-seeds",
        slug: "seeds",
        name_en: "Seeds",
        name_hi: "बीज",
        parentSlug: "agro",
        status: "active",
        searchAliases: ["seeds", "बीज", "hybrid seeds", "crop seeds", "vegetable seeds"],
        relatedTerms: ["Wheat Seeds", "Paddy Seeds", "Vegetable Seeds"],
      },
      {
        id: "sub-agro-tools",
        slug: "tools",
        name_en: "Tools",
        name_hi: "उपकरण",
        parentSlug: "agro",
        status: "active",
        searchAliases: ["tools", "कृषि उपकरण", "farm tools", "implements", "sprayers"],
        relatedTerms: ["Sprayers", "Sickles", "Digging Tools"],
      },
      {
        id: "sub-agro-rural",
        slug: "rural-products",
        name_en: "Rural Products",
        name_hi: "ग्रामीण उत्पाद",
        parentSlug: "agro",
        status: "active",
        searchAliases: ["rural products", "ग्रामीण उत्पाद", "cottage produce", "village crafts"],
        relatedTerms: ["Jaggery", "Hand Pounded Grains", "Clay Pottery"],
      },
      {
        id: "sub-agro-other",
        slug: "other-agro-opportunities",
        name_en: "Other Agro Opportunities",
        name_hi: "अन्य कृषि उत्पाद",
        parentSlug: "agro",
        status: "active",
        searchAliases: ["other agro", "अन्य कृषि उत्पाद", "agro trade"],
        relatedTerms: ["Agro Logistics", "Contract Farming"],
      },
    ],
  },

  // 4. MANUFACTURING
  {
    id: "cat-manufacturing",
    slug: "manufacturing",
    name_en: "Manufacturing",
    name_hi: "विनिर्माण",
    parent: null,
    tagline_en: "Made in India Industrial & Handcrafted Goods",
    tagline_hi: "मेक इन इंडिया औद्योगिक एवं हस्तनिर्मित उत्पाद",
    description_en: "Factory production, handcrafted artisan goods, industrial supplies, and verified contract manufacturing units.",
    description_hi: "फैक्ट्री उत्पादन, हस्तशिल्प इकाइयां, औद्योगिक सामग्री और प्रमाणित भारतीय विनिर्माण इकाइयां।",
    image: "/assets/category-textiles.jpg",
    shopifyCollectionHandle: "manufacturing",
    status: "active",
    searchAliases: ["manufacturing", "विनिर्माण", "factory", "made in india", "उद्योग", "उत्पादन"],
    relatedTerms: ["Handmade", "Factory Products", "Industrial", "Packaging & Paper Products"],
    subcategories: [
      {
        id: "sub-mfg-madeinindia",
        slug: "made-in-india",
        name_en: "Made in India",
        name_hi: "मेड इन इंडिया",
        parentSlug: "manufacturing",
        status: "active",
        searchAliases: ["made in india", "मेड इन इंडिया", "make in india", "swadeshi"],
        relatedTerms: ["Indigenous Goods", "Indian Industry"],
      },
      {
        id: "sub-mfg-handmade",
        slug: "handmade-products",
        name_en: "Handmade Products",
        name_hi: "हस्तनिर्मित उत्पाद",
        parentSlug: "manufacturing",
        status: "active",
        searchAliases: ["handmade", "handmade products", "हस्तनिर्मित", "हस्तशिल्प", "artisan"],
        relatedTerms: ["Brass Urli", "Handloom Silk", "Carved Woodwork"],
      },
      {
        id: "sub-mfg-factory",
        slug: "factory-products",
        name_en: "Factory Products",
        name_hi: "फैक्ट्री उत्पाद",
        parentSlug: "manufacturing",
        status: "active",
        searchAliases: ["factory products", "फैक्ट्री उत्पाद", "mill goods", "mass manufacturing"],
        relatedTerms: ["Uniform Fabric", "Commercial Bottles"],
      },
      {
        id: "sub-mfg-industrial",
        slug: "industrial-products",
        name_en: "Industrial Products",
        name_hi: "औद्योगिक उत्पाद",
        parentSlug: "manufacturing",
        status: "active",
        searchAliases: ["industrial products", "औद्योगिक उत्पाद", "plant supplies", "hardware"],
        relatedTerms: ["Fasteners", "Packaging Rolls", "Industrial Materials"],
      },
      {
        id: "sub-mfg-pkg",
        slug: "packaging-paper-products",
        name_en: "Packaging & Paper Products",
        name_hi: "पैकेजिंग एवं पेपर उत्पाद",
        parentSlug: "manufacturing",
        status: "active",
        searchAliases: ["packaging paper products", "पैकेजिंग एवं पेपर उत्पाद", "paper packaging"],
        relatedTerms: ["Corrugated Boxes", "Kraft Bags"],
      },
      {
        id: "sub-mfg-other",
        slug: "other-manufacturing-products",
        name_en: "Other Manufacturing Products",
        name_hi: "अन्य विनिर्माण उत्पाद",
        parentSlug: "manufacturing",
        status: "active",
        searchAliases: ["other manufacturing", "अन्य विनिर्माण उत्पाद"],
        relatedTerms: ["Custom Fabrication"],
      },
    ],
  },

  // 5. LOGISTICS
  {
    id: "cat-logistics",
    slug: "logistics",
    name_en: "Logistics",
    name_hi: "लॉजिस्टिक्स",
    parent: null,
    tagline_en: "Reliable B2B Dispatch & Hyperlocal Delivery",
    tagline_hi: "विश्वसनीय थोक माल परिवहन एवं हाइपरलोकल पूर्ति",
    description_en: "End-to-end commercial freight, district warehousing, dispatch tracking, and upcoming hyperlocal delivery channels.",
    description_hi: "वाणिज्यिक माल परिवहन, जिला स्तरीय भंडारण, प्रेषण ट्रैकिंग और आधुनिक डिलीवरी समाधान।",
    image: "/assets/hero-editorial.jpg",
    shopifyCollectionHandle: "logistics",
    status: "active",
    searchAliases: ["logistics", "लॉजिस्टिक्स", "delivery", "dispatch", "freight", "transport"],
    relatedTerms: ["B2B Freight", "Hyperlocal Delivery", "Warehousing", "Tracking"],
    subcategories: [
      {
        id: "sub-log-freight",
        slug: "b2b-freight",
        name_en: "B2B Freight",
        name_hi: "थोक माल परिवहन",
        parentSlug: "logistics",
        status: "active",
        searchAliases: ["b2b freight", "थोक माल परिवहन", "cargo", "commercial transport"],
        relatedTerms: ["Truckload", "Part Load"],
      },
      {
        id: "sub-log-hyperlocal",
        slug: "hyperlocal-delivery",
        name_en: "Hyperlocal Delivery",
        name_hi: "हाइपरलोकल डिलीवरी",
        parentSlug: "logistics",
        status: "coming_soon",
        searchAliases: ["hyperlocal delivery", "हाइपरलोकल डिलीवरी", "same day delivery", "local delivery"],
        relatedTerms: ["Neighborhood Express", "Doorstep Dispatch"],
      },
      {
        id: "sub-log-warehouse",
        slug: "warehousing-storage",
        name_en: "Warehousing & Storage",
        name_hi: "गोदाम एवं भंडारण",
        parentSlug: "logistics",
        status: "active",
        searchAliases: ["warehousing", "storage", "गोदाम", "भंडारण"],
        relatedTerms: ["Safe Storage", "Transit Hubs"],
      },
      {
        id: "sub-log-tracking",
        slug: "tracking-dispatch",
        name_en: "Tracking & Dispatch",
        name_hi: "ट्रैकिंग एवं प्रेषण",
        parentSlug: "logistics",
        status: "active",
        searchAliases: ["tracking", "dispatch", "ट्रैकिंग", "प्रेषण", "shipment tracking"],
        relatedTerms: ["Consignment Status", "Live Updates"],
      },
    ],
  },

  // 6. EXPORTS
  {
    id: "cat-exports",
    slug: "exports",
    name_en: "Exports",
    name_hi: "निर्यात",
    parent: null,
    tagline_en: "Taking Authentic Indian Goods to Global Markets",
    tagline_hi: "भारतीय प्रामाणिक उत्पादों का वैश्विक निर्यात",
    description_en: "International consignments of handloom textiles, pure brassware, agro produce, and institutional gifting solutions.",
    description_hi: "हथकरघा वस्त्रों, पीतल शिल्पों, कृषि उत्पादों और संस्थागत उपहारों का अंतर्राष्ट्रीय निर्यात।",
    image: "/assets/category-textiles.jpg",
    shopifyCollectionHandle: "exports",
    status: "active",
    searchAliases: ["exports", "निर्यात", "international trade", "global trade", "import export"],
    relatedTerms: ["Textiles Export", "Brass Export", "Global Consignments"],
    subcategories: [
      {
        id: "sub-exp-textiles",
        slug: "textiles-handloom",
        name_en: "Indian Textiles & Handloom",
        name_hi: "भारतीय वस्त्र एवं हथकरघा",
        parentSlug: "exports",
        status: "active",
        searchAliases: ["textiles export", "handloom export", "भारतीय वस्त्र निर्यात", "silk export"],
        relatedTerms: ["Banarasi Silks", "Chanderi Fabrics"],
      },
      {
        id: "sub-exp-agro",
        slug: "agro-export",
        name_en: "Agro Produce Export",
        name_hi: "कृषि उत्पाद निर्यात",
        parentSlug: "exports",
        status: "active",
        searchAliases: ["agro export", "कृषि निर्यात", "spices export", "grain export"],
        relatedTerms: ["Basmati Rice", "Whole Spices"],
      },
      {
        id: "sub-exp-brass",
        slug: "brass-handicrafts",
        name_en: "Brass & Handicrafts",
        name_hi: "पीतल एवं हस्तशिल्प",
        parentSlug: "exports",
        status: "active",
        searchAliases: ["brass export", "handicrafts export", "पीतल शिल्प निर्यात"],
        relatedTerms: ["Artisanal Urli", "Traditional Idols"],
      },
      {
        id: "sub-exp-global",
        slug: "global-inquiries",
        name_en: "Global Inquiries & Consignments",
        name_hi: "वैश्विक निर्यात पूछताछ",
        parentSlug: "exports",
        status: "active",
        searchAliases: ["global inquiries", "वैश्विक निर्यात", "customs container"],
        relatedTerms: ["Custom Clearance", "Port Forwarding"],
      },
    ],
  },

  // 7. E-COMMERCE
  {
    id: "cat-ecommerce",
    slug: "ecommerce",
    name_en: "E-commerce",
    name_hi: "ई-कॉमर्स",
    parent: null,
    tagline_en: "Scalable Direct-to-Consumer & Multi-Category Shop",
    tagline_hi: "ग्राहकों के लिए बहु-श्रेणी डिजिटल खरीदारी",
    description_en: "Comprehensive marketplace catalog spanning festival, apparel, cosmetics, electronics, home decor, and general merchandise.",
    description_hi: "त्योहार, परिधान, कॉस्मेटिक्स, इलेक्ट्रॉनिक्स, होम डेकोर और सामान्य उपयोग की व्यापक डिजिटल दुकान।",
    image: "/assets/hero-editorial.jpg",
    shopifyCollectionHandle: "ecommerce",
    status: "active",
    searchAliases: ["ecommerce", "e-commerce", "ई-कॉमर्स", "shop", "online shopping", "मार्केटप्लेस", "दुकान"],
    relatedTerms: ["Festival Items", "Cosmetics", "Garments", "Electronics", "Fashion", "Mobile", "Packaging"],
    subcategories: [
      { id: "sub-ecom-fest", slug: "festival-items", name_en: "Festival Items", name_hi: "त्योहार सामग्री", parentSlug: "ecommerce", status: "active", searchAliases: ["festival items", "त्योहार सामग्री"], relatedTerms: ["Puja", "Decor"] },
      { id: "sub-ecom-cosmetics", slug: "cosmetics", name_en: "Cosmetics", name_hi: "कॉस्मेटिक्स", parentSlug: "ecommerce", status: "coming_soon", searchAliases: ["cosmetics", "कॉस्मेटिक्स", "makeup", "creams"], relatedTerms: ["Skincare"] },
      { id: "sub-ecom-garments", slug: "garments", name_en: "Garments", name_hi: "परिधान", parentSlug: "ecommerce", status: "active", searchAliases: ["garments", "परिधान", "कपड़े", "apparel", "sarees", "kurtas"], relatedTerms: ["Banarasi Saree", "Dupatta"] },
      { id: "sub-ecom-electronics", slug: "electronics", name_en: "Electronics", name_hi: "इलेक्ट्रॉनिक्स", parentSlug: "ecommerce", status: "coming_soon", searchAliases: ["electronics", "इलेक्ट्रॉनिक्स", "gadgets"], relatedTerms: ["Cables", "Chargers"] },
      { id: "sub-ecom-fashion", slug: "fashion", name_en: "Fashion", name_hi: "फैशन", parentSlug: "ecommerce", status: "active", searchAliases: ["fashion", "फैशन", "clothing", "wear"], relatedTerms: ["Ethnic Wear"] },
      { id: "sub-ecom-mobile", slug: "mobile", name_en: "Mobile", name_hi: "मोबाइल", parentSlug: "ecommerce", status: "coming_soon", searchAliases: ["mobile", "मोबाइल", "phone accessories"], relatedTerms: ["Cases", "Holders"] },
      { id: "sub-ecom-beauty", slug: "beauty", name_en: "Beauty", name_hi: "ब्यूटी", parentSlug: "ecommerce", status: "coming_soon", searchAliases: ["beauty", "ब्यूटी", "personal care"], relatedTerms: ["Grooming"] },
      { id: "sub-ecom-home", slug: "home", name_en: "Home", name_hi: "होम", parentSlug: "ecommerce", status: "active", searchAliases: ["home", "होम", "home decor"], relatedTerms: ["Urli", "Lamps"] },
      { id: "sub-ecom-toys", slug: "toys", name_en: "Toys", name_hi: "खिलौने", parentSlug: "ecommerce", status: "coming_soon", searchAliases: ["toys", "खिलौने", "wooden toys"], relatedTerms: ["Traditional Toys"] },
      { id: "sub-ecom-baby", slug: "baby", name_en: "Baby", name_hi: "बेबी केयर", parentSlug: "ecommerce", status: "coming_soon", searchAliases: ["baby", "बेबी केयर", "infant care"], relatedTerms: ["Baby Towels"] },
      { id: "sub-ecom-food", slug: "food-kirana", name_en: "Food & Kirana", name_hi: "खाद्य एवं किराना", parentSlug: "ecommerce", status: "coming_soon", searchAliases: ["food", "kirana", "खाद्य", "किराना"], relatedTerms: ["Spices", "Dry Fruits"] },
      { id: "sub-ecom-sports", slug: "sports", name_en: "Sports", name_hi: "खेलकूद", parentSlug: "ecommerce", status: "coming_soon", searchAliases: ["sports", "खेलकूद", "fitness"], relatedTerms: ["Yoga Mats"] },
      { id: "sub-ecom-furniture", slug: "furniture", name_en: "Furniture", name_hi: "फर्नीचर", parentSlug: "ecommerce", status: "coming_soon", searchAliases: ["furniture", "फर्नीचर", "wooden furniture"], relatedTerms: ["Stools", "Chowki"] },
      { id: "sub-ecom-books", slug: "books", name_en: "Books", name_hi: "पुस्तकें", parentSlug: "ecommerce", status: "coming_soon", searchAliases: ["books", "पुस्तकें", "religious books", "diaries"], relatedTerms: ["Vrat Katha"] },
      { id: "sub-ecom-twowheeler", slug: "two-wheeler", name_en: "Two-Wheeler", name_hi: "टू-व्हीलर", parentSlug: "ecommerce", status: "coming_soon", searchAliases: ["two-wheeler", "टू-व्हीलर", "bike accessories"], relatedTerms: ["Helmets", "Covers"] },
      { id: "sub-ecom-pkg", slug: "packaging-paper-products-ecom", name_en: "Packaging & Paper Products", name_hi: "पैकेजिंग एवं पेपर उत्पाद", parentSlug: "ecommerce", status: "active", searchAliases: ["packaging paper products", "पैकेजिंग एवं पेपर उत्पाद"], relatedTerms: ["Paper Bags", "Boxes"] },
      { id: "sub-ecom-other", slug: "other-categories", name_en: "Other Categories", name_hi: "अन्य श्रेणियाँ", parentSlug: "ecommerce", status: "active", searchAliases: ["other categories", "अन्य श्रेणियाँ"], relatedTerms: ["General Goods"] },
    ],
  },

  // 8. PACKAGING & PAPER PRODUCTS (New Mandatory Category)
  {
    id: "cat-packaging",
    slug: "packaging",
    name_en: "Packaging & Paper Products",
    name_hi: "पैकेजिंग एवं पेपर उत्पाद",
    parent: null,
    tagline_en: "Eco-Friendly Paper Bags, Corrugated Boxes & Custom Packaging",
    tagline_hi: "पर्यावरण-अनुकूल पेपर बैग, कार्टन बॉक्स एवं कस्टम पैकेजिंग",
    description_en: "Sustainable paper packaging solutions, gift presentation boxes, retail carry bags, and commercial print packaging for businesses.",
    description_hi: "टिकाऊ कागज़ पैकेजिंग समाधान, उपहार बॉक्स, खुदरा कैरी बैग और व्यवसायों के लिए व्यावसायिक प्रिंट पैकेजिंग।",
    image: "/assets/category-stationery.jpg",
    shopifyCollectionHandle: "packaging",
    status: "active",
    searchAliases: [
      "packaging",
      "paper products",
      "packaging & paper products",
      "packaging and paper products",
      "पैकेजिंग",
      "पेपर उत्पाद",
      "पैकेजिंग एवं पेपर उत्पाद",
      "कागज़ के उत्पाद",
      "कागज़ उत्पाद",
      "paper bags",
      "kraft bags",
      "carry bags",
      "boxes",
      "corrugated boxes",
      "gift packaging",
      "sweet boxes",
    ],
    relatedTerms: [
      "Paper Bags",
      "Packaging Boxes",
      "Gift Packaging",
      "Food Packaging",
      "Retail Packaging",
      "Custom Packaging",
      "पेपर बैग",
      "पैकेजिंग बॉक्स",
      "गिफ्ट पैकेजिंग",
    ],
    subcategories: [
      {
        id: "sub-pkg-paper-bags",
        slug: "paper-bags",
        name_en: "Paper Bags",
        name_hi: "पेपर बैग",
        parentSlug: "packaging",
        status: "active",
        searchAliases: ["paper bags", "पेपर बैग", "kraft paper bag", "carry bag", "shopping bag", "कागज़ के थैले"],
        relatedTerms: ["Kraft Bags", "Twisted Handle Bags", "Printed Bags"],
      },
      {
        id: "sub-pkg-boxes",
        slug: "packaging-boxes",
        name_en: "Packaging Boxes",
        name_hi: "पैकेजिंग बॉक्स",
        parentSlug: "packaging",
        status: "active",
        searchAliases: ["packaging boxes", "पैकेजिंग बॉक्स", "corrugated boxes", "carton", "गत्ते के डिब्बे"],
        relatedTerms: ["Shipping Cartons", "Master Boxes", "Die Cut Boxes"],
      },
      {
        id: "sub-pkg-paper-prod",
        slug: "paper-products",
        name_en: "Paper Products",
        name_hi: "कागज़ उत्पाद",
        parentSlug: "packaging",
        status: "active",
        searchAliases: ["paper products", "पेपर उत्पाद", "कागज़ उत्पाद", "कागज़ के उत्पाद", "stationery paper", "kraft sheets"],
        relatedTerms: ["Wrapping Sheets", "Craft Paper"],
      },
      {
        id: "sub-pkg-gift",
        slug: "gift-packaging",
        name_en: "Gift Packaging",
        name_hi: "उपहार पैकेजिंग",
        parentSlug: "packaging",
        status: "active",
        searchAliases: ["gift packaging", "उपहार पैकेजिंग", "gift boxes", "festive boxes", "rigid boxes"],
        relatedTerms: ["Rigid Luxury Boxes", "Foil Stamped Envelopes"],
      },
      {
        id: "sub-pkg-food",
        slug: "food-packaging",
        name_en: "Food Packaging",
        name_hi: "खाद्य पैकेजिंग",
        parentSlug: "packaging",
        status: "active",
        searchAliases: ["food packaging", "खाद्य पैकेजिंग", "sweet box", "mithai box", "food containers"],
        relatedTerms: ["Mithai Boxes", "Dry Fruit Trays", "Cake Boxes"],
      },
      {
        id: "sub-pkg-retail",
        slug: "retail-packaging",
        name_en: "Retail Packaging",
        name_hi: "खुदरा पैकेजिंग",
        parentSlug: "packaging",
        status: "active",
        searchAliases: ["retail packaging", "खुदरा पैकेजिंग", "garment boxes", "saree boxes", "shoe boxes"],
        relatedTerms: ["Saree Boxes", "Apparel Bags"],
      },
      {
        id: "sub-pkg-office",
        slug: "office-paper-products",
        name_en: "Office Paper Products",
        name_hi: "कार्यालय पेपर उत्पाद",
        parentSlug: "packaging",
        status: "active",
        searchAliases: ["office paper products", "कार्यालय पेपर उत्पाद", "envelopes", "letterheads", "notepads"],
        relatedTerms: ["Envelopes", "Notepads", "Registers"],
      },
      {
        id: "sub-pkg-custom",
        slug: "custom-packaging",
        name_en: "Custom Packaging",
        name_hi: "कस्टम पैकेजिंग",
        parentSlug: "packaging",
        status: "active",
        searchAliases: ["custom packaging", "कस्टम पैकेजिंग", "custom printed boxes", "branding boxes"],
        relatedTerms: ["Logo Printed Bags", "Custom Die Cuts"],
      },
      {
        id: "sub-pkg-other",
        slug: "other-packaging-products",
        name_en: "Other Packaging Products",
        name_hi: "अन्य पैकेजिंग उत्पाद",
        parentSlug: "packaging",
        status: "active",
        searchAliases: ["other packaging products", "अन्य पैकेजिंग उत्पाद", "packaging tape", "bubble wrap"],
        relatedTerms: ["Packing Tapes", "Protective Fillers"],
      },
    ],
  },
];

// Helper to look up category by slug or alias
export function findCategoryBySlug(slug: string): CategoryDef | undefined {
  const normalized = slug.toLowerCase().trim();
  // Direct match
  const direct = CATEGORIES_TAXONOMY.find((c) => c.slug === normalized);
  if (direct) return direct;

  // Compatibility aliases
  const aliasMap: Record<string, string> = {
    "gift-hampers": "festival",
    "puja-samagri": "festival",
    "festival-decoration": "festival",
    "wedding-marriage-items": "festival",
    "handicraft": "manufacturing",
    "home-decoration": "retail",
    "gift-items": "festival",
    "household-products": "retail",
    "other-categories": "ecommerce",
    "textiles-fabrics": "ecommerce",
    "stationery-office": "retail",
    "packaging-paper-products": "packaging",
  };
  const targetSlug = aliasMap[normalized];
  if (targetSlug) {
    return CATEGORIES_TAXONOMY.find((c) => c.slug === targetSlug);
  }

  // Check subcategory matches
  for (const cat of CATEGORIES_TAXONOMY) {
    if (cat.subcategories.some((sub) => sub.slug === normalized)) {
      return cat;
    }
  }

  return undefined;
}

// Helper to look up subcategory across all categories
export function findSubcategoryBySlug(slug: string): SubcategoryDef | undefined {
  const normalized = slug.toLowerCase().trim();
  for (const cat of CATEGORIES_TAXONOMY) {
    const sub = cat.subcategories.find((s) => s.slug === normalized);
    if (sub) return sub;
  }
  return undefined;
}
