// BHAYA INDIA — Search Intent Configuration & Alias Taxonomy
// Extensible intent clusters linking natural search phrases to Parent Categories,
// Subcategories, Shopify Collections, and future marketplace verticals.

export interface SearchIntentCluster {
  id: string;
  parentCategorySlug: string;
  parentCategoryName: { en: string; hi: string };
  subcategorySlug?: string;
  subcategoryName?: { en: string; hi: string };
  shopifyCollectionHandle?: string;
  aliases: string[];
  relatedTerms: string[];
  status: "active" | "coming_soon";
  isFutureCategory?: boolean;
}

export const SEARCH_INTENT_CLUSTERS: SearchIntentCluster[] = [
  // 1. FESTIVAL CLUSTER
  {
    id: "intent-festival",
    parentCategorySlug: "festival",
    parentCategoryName: { en: "Festival", hi: "त्योहार" },
    shopifyCollectionHandle: "festival",
    status: "active",
    aliases: [
      "festival",
      "festivals",
      "त्योहार",
      "त्यौहार",
      "उत्सव",
      "पर्व",
      "festive",
      "tyohar",
      "utsav",
      "parv",
      "parva",
    ],
    relatedTerms: [
      "Puja Items",
      "Holi",
      "Diwali",
      "Navratri",
      "Ganesh Puja",
      "Karwa Chauth",
      "Festival Decoration",
      "Wedding & Marriage Items",
      "Gift Items",
      "पूजा सामग्री",
      "होली",
      "दिवाली",
      "नवरात्र",
      "गणेश पूजा",
      "करवा चौथ",
      "त्योहार सजावट",
      "विवाह एवं शादी सामग्री",
      "उपहार सामग्री",
    ],
  },

  // 2. KARWA CHAUTH CLUSTER
  {
    id: "intent-karwa-chauth",
    parentCategorySlug: "festival",
    parentCategoryName: { en: "Festival", hi: "त्योहार" },
    subcategorySlug: "karwa-chauth",
    subcategoryName: { en: "Karwa Chauth", hi: "करवा चौथ" },
    shopifyCollectionHandle: "karwa-chauth",
    status: "active",
    aliases: [
      "karwa chauth",
      "karva chauth",
      "karwachauth",
      "karvachauth",
      "करवा चौथ",
      "करवा",
      "karwa",
      "karva",
      "karwa chauth thali",
      "करवा चौथ थाली",
      "छलनी",
      "channi",
      "chalni",
      "chhalni",
      "करवा लोटा",
      "sargi",
      "sargi hamper",
      "vrat samagri",
      "करवा चौथ गिफ्ट",
      "karwa chauth gift",
      "karwa chauth gifts",
    ],
    relatedTerms: [
      "Karwa Chauth Thali",
      "करवा चौथ थाली",
      "Karwa",
      "करवा",
      "Puja Samagri",
      "पूजा सामग्री",
      "Festival Decoration",
      "त्योहार सजावट",
      "Gift Items",
      "उपहार सामग्री",
      "Vrat Katha Book",
      "Chalni",
    ],
  },

  // 3. DIWALI CLUSTER
  {
    id: "intent-diwali",
    parentCategorySlug: "festival",
    parentCategoryName: { en: "Festival", hi: "त्योहार" },
    subcategorySlug: "diwali",
    subcategoryName: { en: "Diwali", hi: "दिवाली" },
    shopifyCollectionHandle: "diwali",
    status: "active",
    aliases: [
      "diwali",
      "deepavali",
      "deepawali",
      "दिवाली",
      "दीपावली",
      "दीपक",
      "diya",
      "diyas",
      "दीये",
      "पीतल के दीये",
      "brass diya",
      "लक्ष्मी पूजा",
      "lakshmi puja",
      "festive lights",
      "deep",
      "deepak",
    ],
    relatedTerms: [
      "Brass Diya",
      "Lakshmi Ganesh Idol",
      "Toran",
      "तोरण",
      "Puja Samagri",
      "पूजा सामग्री",
      "Gift Hampers",
      "उपहार",
    ],
  },

  // 4. HOLI CLUSTER
  {
    id: "intent-holi",
    parentCategorySlug: "festival",
    parentCategoryName: { en: "Festival", hi: "त्योहार" },
    subcategorySlug: "holi",
    subcategoryName: { en: "Holi", hi: "होली" },
    shopifyCollectionHandle: "holi",
    status: "active",
    aliases: [
      "holi",
      "holy",
      "होली",
      "रंग",
      "गुलाल",
      "gulal",
      "पिचकारी",
      "pichkari",
      "herbal gulal",
      "organic colors",
      "holi hampers",
      "water gun",
      "thandai",
    ],
    relatedTerms: [
      "Herbal Gulal",
      "Pichkari",
      "Holi Hampers",
      "Organic Colors",
      "गुलाल",
      "त्योहार उपहार",
    ],
  },

  // 5. GANESH PUJA / GANPATI CLUSTER
  {
    id: "intent-ganesh-puja",
    parentCategorySlug: "festival",
    parentCategoryName: { en: "Festival", hi: "त्योहार" },
    subcategorySlug: "ganesh-puja",
    subcategoryName: { en: "Ganesh Puja", hi: "गणेश पूजा" },
    shopifyCollectionHandle: "ganesh-puja",
    status: "active",
    aliases: [
      "ganesh puja",
      "ganesh",
      "ganpati",
      "ganesha",
      "ganesh utsav",
      "ganesh chaturthi",
      "गणेश पूजा",
      "गणपति",
      "गणेश",
      "गणेश चतुर्थी",
      "गणपति बप्पा",
      "vinayaka",
      "मोदक",
      "modak",
      "ganpati idol",
    ],
    relatedTerms: [
      "Ganesh Idol",
      "गणेश मूर्ति",
      "Modak Mould",
      "मोदक सांचा",
      "Puja Thali",
      "पूजा थाली",
      "Havan Samagri",
      "हवन सामग्री",
    ],
  },

  // 6. NAVRATRI CLUSTER
  {
    id: "intent-navratri",
    parentCategorySlug: "festival",
    parentCategoryName: { en: "Festival", hi: "त्योहार" },
    subcategorySlug: "navratri",
    subcategoryName: { en: "Navratri", hi: "नवरात्र" },
    shopifyCollectionHandle: "navratri",
    status: "active",
    aliases: [
      "navratri",
      "navratra",
      "navaratri",
      "नवरात्र",
      "नवरात्रि",
      "durga puja",
      "दुर्गा पूजा",
      "mata ki chunri",
      "mata chunri",
      "माता की चुनरी",
      "dandiya",
      "डांडिया",
      "garba",
      "vrat samagri",
      "व्रत सामग्री",
      "fasting items",
    ],
    relatedTerms: [
      "Mata Ki Chunri",
      "Dandiya Sticks",
      "Akhand Jyot",
      "Puja Samagri",
      "पूजा सामग्री",
      "Vrat Samagri",
    ],
  },

  // 7. WEDDING / SHAADI / VIVAAH CLUSTER
  {
    id: "intent-wedding",
    parentCategorySlug: "festival",
    parentCategoryName: { en: "Festival", hi: "त्योहार" },
    subcategorySlug: "wedding-marriage-items",
    subcategoryName: { en: "Wedding & Marriage Related Items", hi: "विवाह एवं शादी संबंधी सामग्री" },
    shopifyCollectionHandle: "wedding-marriage-items",
    status: "active",
    aliases: [
      "wedding",
      "marriage",
      "shaadi",
      "shadi",
      "vivaah",
      "vivah",
      "शादी",
      "विवाह",
      "वेडिंग",
      "विवाह सामग्री",
      "शादी सामग्री",
      "शुभ विवाह",
      "shagun",
      "shagun envelope",
      "shagun envelopes",
      "शगुन लिफाफे",
      "शगुन लिफाफा",
      "bridal trunks",
      "bridal kit",
      "wedding gifts",
      "haldi platter",
    ],
    relatedTerms: [
      "Shagun Envelopes",
      "Bridal Trunks",
      "Haldi Kumkum",
      "Wedding Favors",
      "शगुन बॉक्स",
      "उपहार सामग्री",
    ],
  },

  // 8. GIFT / UPHAR CLUSTER
  {
    id: "intent-gift",
    parentCategorySlug: "festival",
    parentCategoryName: { en: "Festival", hi: "त्योहार" },
    subcategorySlug: "gift-items",
    subcategoryName: { en: "Gift Items", hi: "उपहार सामग्री" },
    shopifyCollectionHandle: "gift-items",
    status: "active",
    aliases: [
      "gift",
      "gifts",
      "gift items",
      "उपहार",
      "उपहार सामग्री",
      "गिफ्ट",
      "गिफ्ट आइटम",
      "uphar",
      "return gifts",
      "return gift",
      "corporate gift",
      "corporate gifts",
      "gift hampers",
      "festive gifts",
      "hampers",
      "हैम्पर्स",
      "त्योहार उपहार",
    ],
    relatedTerms: [
      "Festival Hampers",
      "Personalized Boxes",
      "Return Gifts",
      "Corporate Gifting",
      "त्योहार हैम्पर्स",
      "ड्राई फ्रूट बॉक्स",
    ],
  },

  // 9. PUJA / PUJA SAMAGRI CLUSTER
  {
    id: "intent-puja",
    parentCategorySlug: "festival",
    parentCategoryName: { en: "Festival", hi: "त्योहार" },
    subcategorySlug: "puja-items",
    subcategoryName: { en: "Puja Items", hi: "पूजा सामग्री" },
    shopifyCollectionHandle: "puja-samagri",
    status: "active",
    aliases: [
      "puja",
      "pooja",
      "puja items",
      "pooja items",
      "puja samagri",
      "pooja samagri",
      "पूजा",
      "पूजा सामग्री",
      "हवन सामग्री",
      "havan",
      "havan samagri",
      "brass diya",
      "diya",
      "camphor",
      "kapoor",
      "dhoop",
      "agarbatti",
      "aasan",
      "puja aasan",
      "roli",
      "akshat",
      "gangajal",
    ],
    relatedTerms: [
      "Brass Diya",
      "Incense",
      "Havan Kund",
      "Puja Thali",
      "पीतल के दीये",
      "हवन किट",
      "पूजा आसन",
    ],
  },

  // 10. FESTIVAL DECORATION CLUSTER
  {
    id: "intent-fest-decor",
    parentCategorySlug: "festival",
    parentCategoryName: { en: "Festival", hi: "त्योहार" },
    subcategorySlug: "festival-decoration",
    subcategoryName: { en: "Festival Decoration", hi: "त्योहार सजावट" },
    shopifyCollectionHandle: "festival-decoration",
    status: "active",
    aliases: [
      "festival decoration",
      "festive decor",
      "त्योहार सजावट",
      "सजावट",
      "तोरण",
      "बंदनवार",
      "toran",
      "bandhanwar",
      "door hanging",
      "fairy lights",
      "rangoli",
      "rangoli colors",
      "urli",
      "brass urli",
    ],
    relatedTerms: [
      "Toran",
      "Bandhanwar",
      "Decorative Urli",
      "Floating Candles",
      "तोरण",
      "रंगोली",
    ],
  },

  // 11. PACKAGING CLUSTER
  {
    id: "intent-packaging",
    parentCategorySlug: "packaging",
    parentCategoryName: { en: "Packaging & Paper Products", hi: "पैकेजिंग एवं पेपर उत्पाद" },
    subcategorySlug: "packaging-boxes",
    subcategoryName: { en: "Packaging Boxes", hi: "पैकेजिंग बॉक्स" },
    shopifyCollectionHandle: "packaging",
    status: "active",
    aliases: [
      "packaging",
      "पैकेजिंग",
      "packaging boxes",
      "पैकेजिंग बॉक्स",
      "corrugated boxes",
      "carton",
      "गत्ते के डिब्बे",
      "डिब्बे",
      "gift boxes",
      "sweet boxes",
      "mithai box",
      "food packaging",
      "खाद्य पैकेजिंग",
      "retail packaging",
      "खुदरा पैकेजिंग",
      "custom packaging",
      "कस्टम पैकेजिंग",
    ],
    relatedTerms: [
      "Paper Bags",
      "Packaging Boxes",
      "Paper Products",
      "पेपर बैग",
      "पैकेजिंग बॉक्स",
      "गिफ्ट पैकेजिंग",
      "Corrugated Boxes",
    ],
  },

  // 12. PAPER PRODUCTS CLUSTER
  {
    id: "intent-paper-products",
    parentCategorySlug: "packaging",
    parentCategoryName: { en: "Packaging & Paper Products", hi: "पैकेजिंग एवं पेपर उत्पाद" },
    subcategorySlug: "paper-products",
    subcategoryName: { en: "Paper Products", hi: "कागज़ उत्पाद" },
    shopifyCollectionHandle: "packaging",
    status: "active",
    aliases: [
      "paper products",
      "पेपर उत्पाद",
      "कागज़ के उत्पाद",
      "कागज़ उत्पाद",
      "कागज के उत्पाद",
      "paper bags",
      "पेपर बैग",
      "kraft bags",
      "kraft paper",
      "carry bags",
      "shopping bags",
      "कागज़ के थैले",
      "office paper",
      "stationery paper",
      "office paper products",
      "कार्यालय पेपर उत्पाद",
    ],
    relatedTerms: [
      "Paper Bags",
      "Wrapping Sheets",
      "Kraft Paper Bags",
      "पेपर बैग",
      "पैकेजिंग",
      "कागज़ के डिब्बे",
    ],
  },

  // 13. RETAIL CATEGORY
  {
    id: "intent-retail",
    parentCategorySlug: "retail",
    parentCategoryName: { en: "Retail", hi: "रिटेल" },
    shopifyCollectionHandle: "retail",
    status: "active",
    aliases: ["retail", "रिटेल", "खुदरा", "general store", "household", "home goods", "दैनिक उपयोग"],
    relatedTerms: ["Daily Use", "Household", "Kitchen", "General Store", "घरेलू उत्पाद"],
  },

  // 14. AGRO CATEGORY
  {
    id: "intent-agro",
    parentCategorySlug: "agro",
    parentCategoryName: { en: "Agro", hi: "कृषि" },
    shopifyCollectionHandle: "agro",
    status: "active",
    aliases: ["agro", "कृषि", "farming", "agriculture", "किसान", "खेती", "spices", "मसाले", "grains"],
    relatedTerms: ["Grains", "Pulses", "Spices", "Organic Farming", "मसाले", "दालें"],
  },

  // 15. MANUFACTURING CATEGORY
  {
    id: "intent-manufacturing",
    parentCategorySlug: "manufacturing",
    parentCategoryName: { en: "Manufacturing", hi: "मैन्युफैक्चरिंग" },
    shopifyCollectionHandle: "manufacturing",
    status: "active",
    aliases: ["manufacturing", "मैन्युफैक्चरिंग", "उद्योग", "उत्पादन", "factory", "handicraft", "हस्तशिल्प"],
    relatedTerms: ["Handicraft", "Industrial Goods", "Textile Units", "हस्तशिल्प"],
  },

  // 16. LOGISTICS CATEGORY
  {
    id: "intent-logistics",
    parentCategorySlug: "logistics",
    parentCategoryName: { en: "Logistics", hi: "लॉजिस्टिक्स" },
    shopifyCollectionHandle: "logistics",
    status: "active",
    aliases: ["logistics", "लॉजिस्टिक्स", "परिवहन", "transport", "freight", "courier", "shipping", "डिलीवरी"],
    relatedTerms: ["Freight", "Warehousing", "Express Cargo", "Last Mile", "परिवहन"],
  },

  // 17. EXPORTS CATEGORY
  {
    id: "intent-exports",
    parentCategorySlug: "exports",
    parentCategoryName: { en: "Exports", hi: "निर्यात" },
    shopifyCollectionHandle: "exports",
    status: "active",
    aliases: ["exports", "निर्यात", "international trade", "global supply", "b2b export"],
    relatedTerms: ["Overseas Consignments", "Customs Clearance", "Bulk Export"],
  },

  // 18. E-COMMERCE CATEGORY
  {
    id: "intent-ecommerce",
    parentCategorySlug: "ecommerce",
    parentCategoryName: { en: "E-commerce", hi: "ई-कॉमर्स" },
    shopifyCollectionHandle: "ecommerce",
    status: "active",
    aliases: ["ecommerce", "e-commerce", "ई-कॉमर्स", "online shopping", "digital store"],
    relatedTerms: ["Direct to Consumer", "Online Catalogue", "Trending Products"],
  },

  // ==========================================
  // FUTURE E-COMMERCE CATEGORIES (Coming Soon)
  // Requirement 20 compatibility
  // ==========================================
  {
    id: "intent-cosmetics",
    parentCategorySlug: "cosmetics",
    parentCategoryName: { en: "Cosmetics", hi: "सौंदर्य प्रसाधन" },
    status: "coming_soon",
    isFutureCategory: true,
    aliases: ["cosmetics", "कॉस्मेटिक्स", "सौंदर्य प्रसाधन", "makeup", "मेकअप", "lipsticks", "skincare"],
    relatedTerms: ["Beauty", "Skincare", "Personal Care"],
  },
  {
    id: "intent-garments",
    parentCategorySlug: "garments",
    parentCategoryName: { en: "Garments", hi: "गारमेंट्स" },
    status: "coming_soon",
    isFutureCategory: true,
    aliases: ["garments", "गारमेंट्स", "कपड़े", "clothing", "apparel", "shirts", "kurtas"],
    relatedTerms: ["Fashion", "Ethnic Wear", "Textiles"],
  },
  {
    id: "intent-electronics",
    parentCategorySlug: "electronics",
    parentCategoryName: { en: "Electronics", hi: "इलेक्ट्रॉनिक्स" },
    status: "coming_soon",
    isFutureCategory: true,
    aliases: ["electronics", "इलेक्ट्रॉनिक्स", "बिजली के सामान", "gadgets", "appliances"],
    relatedTerms: ["Gadgets", "Home Appliances", "Accessories"],
  },
  {
    id: "intent-fashion",
    parentCategorySlug: "fashion",
    parentCategoryName: { en: "Fashion", hi: "फैशन" },
    status: "coming_soon",
    isFutureCategory: true,
    aliases: ["fashion", "फैशन", "fashion wear", "style", "accessories"],
    relatedTerms: ["Garments", "Footwear", "Watches"],
  },
  {
    id: "intent-mobile",
    parentCategorySlug: "mobile",
    parentCategoryName: { en: "Mobile", hi: "मोबाइल" },
    status: "coming_soon",
    isFutureCategory: true,
    aliases: ["mobile", "मोबाइल", "smartphone", "phone", "mobile accessories", "charger"],
    relatedTerms: ["Smartphones", "Covers", "Cables"],
  },
  {
    id: "intent-beauty",
    parentCategorySlug: "beauty",
    parentCategoryName: { en: "Beauty", hi: "ब्यूटी" },
    status: "coming_soon",
    isFutureCategory: true,
    aliases: ["beauty", "ब्यूटी", "सौंदर्य", "beauty products", "wellness"],
    relatedTerms: ["Cosmetics", "Personal Care"],
  },
  {
    id: "intent-home",
    parentCategorySlug: "home",
    parentCategoryName: { en: "Home", hi: "होम" },
    status: "coming_soon",
    isFutureCategory: true,
    aliases: ["home", "होम", "home decor", "गृह सज्जा", "furnishing", "bedsheets"],
    relatedTerms: ["Living Room", "Bedding", "Decor"],
  },
  {
    id: "intent-toys",
    parentCategorySlug: "toys",
    parentCategoryName: { en: "Toys", hi: "खिलौने" },
    status: "coming_soon",
    isFutureCategory: true,
    aliases: ["toys", "टॉयज", "खिलौने", "kids toys", "games", "puzzles"],
    relatedTerms: ["Educational Toys", "Board Games"],
  },
  {
    id: "intent-baby",
    parentCategorySlug: "baby",
    parentCategoryName: { en: "Baby", hi: "शिशु उत्पाद" },
    status: "coming_soon",
    isFutureCategory: true,
    aliases: ["baby", "बेबी", "शिशु उत्पाद", "baby care", "diapers", "infant"],
    relatedTerms: ["Baby Clothing", "Care Products"],
  },
  {
    id: "intent-food-kirana",
    parentCategorySlug: "food-kirana",
    parentCategoryName: { en: "Food & Kirana", hi: "खाद्य एवं किराना" },
    status: "coming_soon",
    isFutureCategory: true,
    aliases: ["food", "kirana", "किराना", "खाद्य सामग्री", "grocery", "दाल", "चावल", "तेल"],
    relatedTerms: ["Grains", "Oil", "Staples"],
  },
  {
    id: "intent-sports",
    parentCategorySlug: "sports",
    parentCategoryName: { en: "Sports", hi: "खेल सामग्री" },
    status: "coming_soon",
    isFutureCategory: true,
    aliases: ["sports", "स्पोर्ट्स", "खेल सामग्री", "fitness", "gym", "cricket"],
    relatedTerms: ["Fitness Gear", "Athletic Equipment"],
  },
  {
    id: "intent-furniture",
    parentCategorySlug: "furniture",
    parentCategoryName: { en: "Furniture", hi: "फर्नीचर" },
    status: "coming_soon",
    isFutureCategory: true,
    aliases: ["furniture", "फर्नीचर", "लकड़ी का सामान", "tables", "chairs", "sofa"],
    relatedTerms: ["Woodcraft", "Home Furniture"],
  },
  {
    id: "intent-books",
    parentCategorySlug: "books",
    parentCategoryName: { en: "Books", hi: "पुस्तकें" },
    status: "coming_soon",
    isFutureCategory: true,
    aliases: ["books", "बुक्स", "किताबें", "पुस्तकें", "literature", "novels", "vrat katha"],
    relatedTerms: ["Devotional Books", "Literature"],
  },
  {
    id: "intent-two-wheeler",
    parentCategorySlug: "two-wheeler",
    parentCategoryName: { en: "Two-Wheeler", hi: "दोपहिया" },
    status: "coming_soon",
    isFutureCategory: true,
    aliases: ["two-wheeler", "two wheeler", "टू व्हीलर", "दोपहिया", "bike", "scooter", "helmet"],
    relatedTerms: ["Automotive", "Helmets", "Riding Gear"],
  },
];
